### ISSUE TITLE
Doesn't work on localhost

### ISSUE THREAD

**Issue by mickkn** [larryworm1127/BoardGames#4]
Hi, do I need to do something special to get this to work on a localhost?

Tried with 

Cloned the repos
set FLASK_APP=run.py
flask run

But the games doesnt work, it displays fine though

**Comment by larryworm1127** [comment]
Sorry to hear about that. Let me look into it. I will get back to you as soon as I figure something out.

**Comment by mickkn** [comment]
Hi, thanks. I must say, that I've only tried with Python 3.8

**Comment by larryworm1127** [comment]
I have just fixed tic tac toe. Apparently it was just my HTML not pointing at the correct fontawesome stylesheet, so all the symbols and buttons aren't showing up. As for sudoku, there's some problem caused by newer versions of python. I will try to fix it when I have time.

Thanks for the feedback!

**Comment by larryworm1127** [comment]
I made a fix for Sudoku. Let me know if it works now.
